language: node_js
node_js:
  - "4"
  - "5"
  - "node"
services:
  - redis-server
before_install:
  - npm config set spin false
  - printf "@npm:registry=https://registry.internal.npmjs.com/\n//registry.internal.npmjs.com/:_authToken=${NPM_TOKEN}\n" >> ~/.npmrc
